### ISSUE TITLE
Who/ How are dwyl events organised?

### ISSUE THREAD

**Issue by Cleop** [dwyl/events#16]
There are loads of ideas for events floating around, what is the procedure for turning them from little ideas to being booked in the diary and happening?

Is there anyone responsible for organising company events or is it the person who has the idea? (ie. just because someone has the idea does that mean they should want to organise it too?)

Who should an organiser turn to to talk about budget? Do we have a budget for these kind of events? Do we get everyone to chip in? If there is a budget or people in, do we have a procedure for reimbursing someone who pays upfront?

**Comment by ghost** [comment]
@cleop there is currently no budget (https://github.com/dwyl/hq/issues/331 https://github.com/dwyl/hq/issues/146) so costs would be divided by participants

Events can be organised by anyone wanting to run one - doesn't have to be the person with the original idea

**Comment by Cleop** [comment]
Closing this issue as @markwilliamfirth has answered my question.

**Comment by ghost** [comment]
Gonna reopen just as a reminder for me to add this to the readme 👍

**Comment by iteles** [comment]
This comment is both false and confusing as things have never been done this way: https://github.com/dwyl/events/issues/16#issuecomment-340393757

Closing to avoid confusion and anyone who  would like to raise an idea for an event/outing can do so in this repo.
