### ISSUE TITLE
Christmas Party / Meal 🎄

### ISSUE THREAD

**Issue by ghost** [dwyl/events#4]
Originally suggested by @Cleop here: https://github.com/dwyl/hq/issues/400

>I really enjoyed the March dinner #213 and think it would be a good idea to have another get together / meal at Christmas 🎄 ☃️

>My suggestion would be a meal at FocusHub on an weeknight evening in the first half of December 2017. We can either pick out an arbitrary date or run a doodle poll if people's availability is already looking patchy. My first arbitrary date suggestions are Weds 6th or Fri 8th Dec.

>This is just an idea so feel free to chime in with suggestions of food or games or other! (@naazy suggested Werewolf)

Expressed interest:
@Jbarget 
@naazy 
@iteles 
@markwilliamfirth

**Comment by Jbarget** [comment]
potential for a combined event with Winter DWYLympics 2017 here too, might need some more imagination than its summer sibling

**Comment by iteles** [comment]
Invite sent out!

So far the list of attendees:
+ @naazy 
+ @NataliaLKB 
+ @Jbarget 
+ @katbow 
+ @ZooeyMiller 
+ @Conorc1000 
+ @Cleop 
+ @RobStallion 
+ _Maybe_ @eliascodes

**Comment by katbow** [comment]
Maybe..c'mon @eliascodes.

**Comment by eliasmalik** [comment]
@katbow lol, I have to facilitate the FAC business meeting that evening 😑

**Comment by katbow** [comment]
@eliascodes well hope to see you there after! ❤️ 

Looking forward to a nice meal with everyone 😄

**Comment by iteles** [comment]
@eliascodes I'll come too and look menacing whenever people take too long to make their point 😉 
I'd forgotten it starts at 18h30 and not at 18h00 like it used to 😒

**Comment by Cleop** [comment]
Maybe/yes from @SimonLab 😉  right?
Yes from @sohilpandya right?

@iteles - how is the food for this being organised? How can we help?

**Comment by iteles** [comment]
@Cleop I'm giving it some thought this weekend! Thanks for asking 😉

**Comment by Cleop** [comment]
Can this one now be closed since the event has passed? @iteles

**Comment by iteles** [comment]
<img width="637" alt="screen shot 2018-01-18 at 11 23 39" src="https://user-images.githubusercontent.com/4185328/35095932-3f50efbc-fc42-11e7-93fe-1a4d579fb6b6.png">
https://twitter.com/dwyl/status/938717767989104641
