### ISSUE TITLE
dwyl summer 2018

### ISSUE THREAD

**Issue by ghost** [dwyl/events#6]
https://github.com/dwyl/summer

**Comment by Cleop** [comment]
@nelsonic @iteles - any idea what month this is likely to be happening this year? 

I'm starting to make summer plans and want to have in mind the dwyl dates for this! I know other people are too!

**Comment by nelsonic** [comment]
@cleop we are thinking mid-to-late July 📆 
however it's not "_finalised_" yet ✏️ 
because there's "_a lot going on_" right now... 😓 

Please re-open this issue in: https://github.com/dwyl/summer/issues/new 🆕 
thanks! 🎉
